name: Test

on:
    issue_comment:

permissions:
    contents: read
    issues: write

jobs:
    process:
        name: Process
        runs-on: ubuntu-latest

        steps:
            - name: Write event payload to file
              run: echo '${{ toJson(github.event) }}' > payload.json

            - name: Echo
              run: cat payload.json

            - name: Process
              uses: dagger/dagger-for-github@29a88e72255e732147ba18a670978b90bcc59efd # v6.4.0
              with:
                  verb: call
                  module: github.com/${{ github.repository }}@${{ github.ref }}
                  args: --github-token env:GITHUB_TOKEN process --event-name ${{ github.event_name }} --payload payload.json
                  version: 0.12.4
              env:
                  GITHUB_TOKEN: ${{ github.token }}
